spring:
  application:
    name: auth-service  # or producer-service, etc.
  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:app_db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
