spring:
  application:
    name: email-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: naijarushh@gmail.com
    password: zkocgbgmclxhkizi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
